# config/sources.yml
sources:
  - name: co_public_drinking_water
    description: Colorado public drinking water quality
    files:
      - data/usa/co/public_drinking_water/public_drinking_water_2026-03-14.csv

    fields:
      state:
        canonical: state_code
        type: text
        on_failure: skip_row
        rules:
          - kind: state_name_to_code
            on_failure: skip_dataset
      county_fips:
        canonical: fips_code
        type: text
      year:
        canonical: year
        type: smallint
      quarter:
        canonical: quarter
        type: smallint
      pws_latitude:
        canonical: latitude
        type: float8
      pws_longitude:
        canonical: longitude
        type: float8
      analyte_name:
        canonical: analyte_name
        type: text
        on_failure: skip_row
      time_period:
        canonical: time_period
        type: text
      average_concentration:
        canonical: average_concentration
        type: float8
      maximum_concentration:
        canonical: maximum_concentration
        type: float8
      sdwa_limit:
        canonical: sdwa_limit
        type: float8
      units:
        canonical: units
        type: text
      pws_id_number:
        canonical: pws_id_number
        type: text
      pws_name:
        canonical: pws_name
        type: text
      pws_primary_source_code:
        canonical: pws_primary_source_code
        type: text
      pws_population_served:
        canonical: pws_population_served
        type: integer

    derived: {}
